server:
  port: 9002

spring:
  application:
    name: DEPARMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

     
#eureka:
#  instance:
#     metadataMap:
#       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#  serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
      
management:
  tracing:
    sampling:
      probability: 1.0